Vielen Dank für die Bestellung&nbsp; # <span style="color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(251, 251, 251); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">{ORDER_ID}</span> in unserem Shop Kitchen-Profi | Deutschland.<br />
<br />
In kurzerer Zeit erhalten Sie von uns eine Bestätigung Ihrer Bestellung mir Lieferfristen und Konditionen.<br />
<br />
Die Zahlung erfolgt wie gewünscht per Vorauskasse.&nbsp;&nbsp; Bitte überweisen Sie den Rechnungsbetrag innerhalb von 14 Tagen auf untenstehendes Konto.<br />
<br />
Empfänger Vialex GmbH<br />
IBAN DE43 5746 0117 0001 2363 65<br />
R-Bank Neuwied-Linz EG<br />
BIC GENODED1NWD<br />
<br />
<br />
Ihre Bestellungsnumer ist: <span style="color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(251, 251, 251); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">{ORDER_ID}</span><br />
Bestellungsdatum: <span style="color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(251, 251, 251); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">{DATE_ORDER}</span>